name: github pages
on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      # Step 1 - Checkout repository
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      # Step 2 - Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      # (Optional) Step 3 - Clean public directory
        # - name: Clean public directory
        #   run: rm -rf public
      # Step 4 - Build Hugo site
      - name: Build
        run: hugo --minify
      # Step 5 - Deploy to external repo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          user_name: ImAKappa
          user_email: imaninconsp1cuouskappa@gmail.com
          publish_branch: gh-pages
          publish_dir: ./public